include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-tinyfm
PKG_VERSION:=2.5.3
PKG_RELEASE:=7

PKG_LICENSE:=MIT
PKG_MAINTAINER:=Yogxx <https://github.com>

LUCI_TITLE:=LuCI support for TinyFM
LUCI_DEPENDS:=+php8 +php8-cgi +php8-fastcgi +php8-fpm \
    +php8-mod-session +php8-mod-ctype +php8-mod-fileinfo \
    +php8-mod-zip +php8-mod-iconv +php8-mod-mbstring \
    +coreutils-stat +zoneinfo-asia
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

define Package/$(PKG_NAME)/description
 LuCI interface for TinyFM file manager.
endef

define Package/$(PKG_NAME)/install
	$(INSTALL_DIR) $(1)/www/tinyfm
	if [ -d ./root ]; then \
		$(CP) ./root/* $(1)/; \
	fi
endef

define Package/$(PKG_NAME)/postinst
#!/bin/sh
if [ -z "$${IPKG_INSTROOT}" ]; then
	mkdir -p /www/tinyfm
	[ -L "/www/tinyfm/rootfs" ] && rm "/www/tinyfm/rootfs"
	[ -L "/www/tinyfm/openclash" ] && rm "/www/tinyfm/openclash"
	
	ln -s / /www/tinyfm/rootfs
	ln -s /etc/openclash/ /www/tinyfm/openclash

	if [ -f /etc/php.ini ]; then
		sed -i 's/^memory_limit.*/memory_limit = 64M/' /etc/php.ini
	fi
	
	uci set uhttpd.main.index_page='index.php'
	uci set uhttpd.main.interpreter='.php=/usr/bin/php-cgi'
	uci commit uhttpd

	/etc/init.d/php8-fpm restart
	/etc/init.d/uhttpd restart
fi
exit 0
endef

define Package/$(PKG_NAME)/prerm
#!/bin/sh
if [ -z "$${IPKG_INSTROOT}" ]; then
	[ -L "/www/tinyfm/rootfs" ] && rm "/www/tinyfm/rootfs"
	[ -L "/www/tinyfm/openclash" ] && rm "/www/tinyfm/openclash"
	
	if [ -f /etc/php.ini ]; then
		sed -i 's/^memory_limit.*/memory_limit = 128M/' /etc/php.ini
	fi

	uci del uhttpd.main.interpreter
	uci commit uhttpd

	/etc/init.d/php8-fpm restart
	/etc/init.d/uhttpd restart
fi
exit 0
endef

$(eval $(call BuildPackage,$(PKG_NAME)))
